"""OECD data fetch helpers for G20 CPI and PPP data."""

from __future__ import annotations

from typing import Any

import pandas as pd
import requests

G20_COUNTRIES = [
    "ARG",
    "AUS",
    "BRA",
    "CAN",
    "CHN",
    "FRA",
    "DEU",
    "IND",
    "IDN",
    "ITA",
    "JPN",
    "KOR",
    "MEX",
    "RUS",
    "SAU",
    "ZAF",
    "TUR",
    "GBR",
    "USA",
    "EU27",
]

COUNTRY_NAMES = {
    "ARG": "아르헨티나",
    "AUS": "호주",
    "BRA": "브라질",
    "CAN": "캐나다",
    "CHN": "중국",
    "FRA": "프랑스",
    "DEU": "독일",
    "IND": "인도",
    "IDN": "인도네시아",
    "ITA": "이탈리아",
    "JPN": "일본",
    "KOR": "대한민국",
    "MEX": "멕시코",
    "RUS": "러시아",
    "SAU": "사우디아라비아",
    "ZAF": "남아프리카공화국",
    "TUR": "튀르키예",
    "GBR": "영국",
    "USA": "미국",
    "EU27": "유럽연합",
}

OECD_API_BASE = "https://sdmx.oecd.org/public/rest/data"


def _stable_offset(country: str, year: int, span: int, base_shift: int) -> float:
    seed = sum(ord(char) for char in country) + year * 17
    return (seed % span) / 100 - base_shift


def fetch_cpi_data(
    countries: list[str] | None = None,
    start_year: int = 2020,
    end_year: int = 2024,
) -> pd.DataFrame:
    """Return placeholder CPI-like data for local development.

    The production static file is generated by ``python/generate_data.py``.
    This helper keeps a stable DataFrame shape for calculator tests and future
    OECD integration work.
    """
    if countries is None:
        countries = G20_COUNTRIES

    data = []
    for country in countries:
        for year in range(start_year, end_year + 1):
            value = (
                100.0
                if country == "KOR"
                else 100 + _stable_offset(country, year, span=8000, base_shift=30)
            )
            data.append(
                {
                    "country_code": country,
                    "country_name": COUNTRY_NAMES.get(country, country),
                    "year": year,
                    "value": round(value, 2),
                    "dataset_type": "CPI",
                }
            )

    return pd.DataFrame(data)


def fetch_ppp_data(
    countries: list[str] | None = None,
    start_year: int = 2020,
    end_year: int = 2024,
) -> pd.DataFrame:
    """Return placeholder PPP-like data for local development."""
    if countries is None:
        countries = G20_COUNTRIES

    data = []
    for country in countries:
        for year in range(start_year, end_year + 1):
            value = (
                100.0
                if country == "KOR"
                else 100 + _stable_offset(country, year, span=6000, base_shift=20)
            )
            data.append(
                {
                    "country_code": country,
                    "country_name": COUNTRY_NAMES.get(country, country),
                    "year": year,
                    "value": round(value, 2),
                    "dataset_type": "PPP",
                }
            )

    return pd.DataFrame(data)


def fetch_oecd_data(
    dataflow_id: str,
    countries: list[str] | None = None,
    start_period: str = "2020",
    end_period: str = "2024",
) -> dict[str, Any]:
    """Call the OECD SDMX API and return the raw JSON response."""
    if countries is None:
        countries = G20_COUNTRIES

    country_str = "+".join(countries)
    url = (
        f"{OECD_API_BASE}/{dataflow_id}/{country_str}.A"
        f"?startPeriod={start_period}&endPeriod={end_period}&format=jsondata"
    )

    try:
        response = requests.get(url, timeout=30)
        response.raise_for_status()
        return response.json()
    except requests.RequestException as exc:
        return {"error": str(exc)}


if __name__ == "__main__":
    print("Testing CPI data fetch...")
    cpi_df = fetch_cpi_data(["KOR", "USA", "JPN"], 2023, 2024)
    print(cpi_df)

    print("\nTesting PPP data fetch...")
    ppp_df = fetch_ppp_data(["KOR", "USA", "JPN"], 2023, 2024)
    print(ppp_df)
